name: kedaipos_mobile
description: "Kedai POS merupakan aplikasi Point of Sales yang dikembangkan oleh Kedai Programmer yang diharapakna dapat membantu UMKM dalam mengembangkan bisnisnya"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
